# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{css_validator_parser}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kevin Menard"]
  s.date = %q{2010-07-16}
  s.email = %q{nirvdrum@gmail.com}
  s.files = [
    ".document",
     ".gitignore",
     "Rakefile",
     "VERSION",
     "lib/css_validator_parser.rb",
     "spec/css_validator_parser_spec.rb",
     "spec/fixtures/embedded_styles_with_warnings.xml",
     "spec/fixtures/multiple_stylesheets_with_errors.xml",
     "spec/fixtures/single_stylesheet_with_errors.xml",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://codaset.com/nirvdrum/css_validation_parser}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Parses SOAP results from the W3C CSS validator.}
  s.test_files = [
    "spec/css_validator_parser_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

